# DO NOT REMOVE THIS
theme = "hyde-hyde"
baseURL = "https://blog.jw910731.wtf/"
languageCode = "en"
title = "jw910731's Blog"

# disqusShortname = "your-disqus-shortname"
googleAnalytics = "UA-178403196-1"

summarylength = 30

[params]
    author = "jw910731"
    title = "jw910731's Blog"
    # description = "..."
    # authorimage = "/img/hugo.png"
    dateformat = "2006/1/1"

    # sidebar, copyright & license
    #logoimage = "/img/hugo.png"
    copyright = "jw910731"
    since = 2020
    #license = "CC BY-SA 4.0"
    #licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true

	# please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    # none, "hugo", or "tocbot"
    #toc = "none"
    math=true
    mainSections=["blog", "course", "post"]

[params.social]
	github = "jw910731"
	bitbucket="jw910731"
	gitlab="jw910731"
	facebook="jw910731"
	email="jw910731@gmail.com"
	stackoverflow="11264533/jw910731"

[[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "Blog"
    url = "/blog"
[[menu.main]]
    identifier = "course"
    name = "course"
    title = "Course"
    url = "/course"


